ditto-lang/ditto

crates/ditto-fmt/src/declaration.rs, crates/ditto-fmt/src/expression.rs
As part of adding `if-then-else` expressions (#21) I realised there are a few _different_ ways we want to format expressions as part of value declarations.
```ditto
-- inline
five = 5;
inline_if = if true then yeh else nah;
-- multiline hanging (calls, arrays...)
hanging_call = some_function(
arg0,
arg1,
arg2,
);
-- multiline newline (if-then-else, let, matches...)
multi_line_if = 
if true then
yeh
else
nah;
```
But this same logic also applies to the function bodies. Hence I've moved [this logic](https://github.com/ditto-lang/ditto/pull/21/commits/4cf578b0b3837ecefe158b787dbd062d475ac700#diff-f327866f2fe0f49b39e831d8eb916383e83d72990b5a1a7fda8f76454fd03f40R44-R79) to a helper function, now used by both value declaration formatting and "lambda" formatting.
=> Format lambda body like value declaration expressions

.github/workflows/ci.yaml
Draft PRs aren't _expected_ to be in a good/working state, so there's no point using valuable GitHub action minutes on them.
=> Don't run expensive workflow jobs for draft PRs

crates/ditto-checker/golden-tests/type-errors/argument_length_mismatch_3.ditto, crates/ditto-checker/golden-tests/type-errors/argument_length_mismatch_3.error, crates/ditto-checker/golden-tests/type-errors/not_a_function_1.ditto, crates/ditto-checker/golden-tests/type-errors/not_a_function_1.error, crates/ditto-checker/golden-tests/type-errors/unification_error_4.ditto, crates/ditto-checker/golden-tests/type-errors/unification_error_4.error, crates/ditto-checker/src/module/value_declarations/mod.rs, crates/ditto-checker/src/typechecker/pre_ast.rs, crates/ditto-checker/src/typechecker/tests/mod.rs, crates/ditto-checker/src/typechecker/tests/right_pipe.rs, crates/ditto-codegen-js/golden-tests/javascript/pipe_expressions.ditto, crates/ditto-codegen-js/golden-tests/javascript/pipe_expressions.js, crates/ditto-cst/src/expression.rs, crates/ditto-cst/src/get_span.rs, crates/ditto-cst/src/parser/expression.rs, crates/ditto-cst/src/parser/grammar.pest, crates/ditto-cst/src/parser/token.rs, crates/ditto-cst/src/token.rs, crates/ditto-fmt/golden-tests/pipe_expressions.ditto, crates/ditto-fmt/src/expression.rs, crates/ditto-fmt/src/has_comments.rs, crates/ditto-fmt/src/token.rs
=> Add the pipe operator `|>`

crates/ditto-ast/src/expression.rs, crates/ditto-ast/src/name.rs, crates/ditto-checker/src/module/value_declarations/mod.rs, crates/ditto-checker/src/typechecker/mod.rs, crates/ditto-checker/src/typechecker/pre_ast.rs, crates/ditto-checker/src/typechecker/substitution.rs, crates/ditto-checker/src/typechecker/tests/function.rs, crates/ditto-checker/src/typechecker/tests/match.rs, crates/ditto-codegen-js/golden-tests/javascript/basic_expressions.ditto, crates/ditto-codegen-js/golden-tests/javascript/basic_expressions.js, crates/ditto-codegen-js/golden-tests/javascript/match_expressions.ditto, crates/ditto-codegen-js/golden-tests/javascript/match_expressions.js, crates/ditto-codegen-js/src/convert.rs, crates/ditto-cst/src/expression.rs, crates/ditto-cst/src/get_span.rs, crates/ditto-cst/src/name.rs, crates/ditto-cst/src/parser/expression.rs, crates/ditto-cst/src/parser/grammar.pest, crates/ditto-cst/src/parser/name.rs, crates/ditto-fmt/golden-tests/match_expressions.ditto, crates/ditto-fmt/src/expression.rs, crates/ditto-fmt/src/has_comments.rs, crates/ditto-fmt/src/name.rs
Currently, any unused value binders raise a warning. For example:
https://github.com/ditto-lang/ditto/blob/53a0eb49485c9ed9b3e2a57885e045bb0a4309e9/crates/ditto-checker/golden-tests/warnings/unused_function_binder.warnings#L2-L9
https://github.com/ditto-lang/ditto/blob/53a0eb49485c9ed9b3e2a57885e045bb0a4309e9/crates/ditto-checker/golden-tests/warnings/unused_pattern_binder.warnings#L2-L11
https://github.com/ditto-lang/ditto/blob/53a0eb49485c9ed9b3e2a57885e045bb0a4309e9/crates/ditto-checker/golden-tests/warnings/unused_effect_binder.warnings#L2-L12
Clearly there are legitimate reasons to ignore a binding, so there needs to be a way to suppress these warnings. Most languages (and/or linters) that I'm aware of handle this by prefixing unused variables with a `_`. 
However this is generally …
=> Add `_unused` names

crates/ditto-cli/fixtures/javascript-project/dist/A_Test.js, crates/ditto-codegen-js/golden-tests/javascript/basic_expressions.js, crates/ditto-codegen-js/golden-tests/javascript/effect_expressions.ditto, crates/ditto-codegen-js/golden-tests/javascript/effect_expressions.js, crates/ditto-codegen-js/golden-tests/javascript/match_expressions.ditto, crates/ditto-codegen-js/golden-tests/javascript/match_expressions.js, crates/ditto-codegen-js/src/convert.rs, crates/ditto-codegen-js/src/optimize/rewrites.rs
This was prompted by seeing that...
```dittoj
huh = (res) -> do {
match res with
| Ok(_) -> some_effect
| Err(_) -> some_effect
};
```
Generates...
```javascript
function huh(res) {
return () => {
return (
res[0] === "Ok"
? some_effect
: res[0] === "Err"
? some_effect
: (() => {
throw new Error("Pattern match error");
})()
)(/* NOTE: here we're calling `some_effect` */);
};
}
```
So I thought it might be sensible to rewrite `(condition ? true_value : false_value)()` to `condition ? true_value() : false_value()` ([see here](https://github.com/ditto-lang/ditto/pull/52/commits/f2b1892362ebb94803ae3f9b0a4357f150b89245#diff-0e5370d93426f70c2a7642df1c3a45b763b03e2f6bba2d5bd1124eb9bdd2c949R324-R366)). But then I realised that can only be legit if the base case (i.e. the `throw`) [is of a …
=> Add some more JavaScript rewrite rules ⚡

.gitignore, Cargo.lock, crates/ditto-cst/benches/expressions.rs, crates/ditto-cst/src/parser/grammar.pest, shell.nix
Nested arrays (`[[[x]]]`) and records (`{ a = { b = { c = {} } } }`) are taking ages to parse (as I discovered [here](https://github.com/ditto-lang/ditto/pull/54/files#diff-2e12ac3b8b2ed016987c0887d58af21bab1b8bb9586d5681194eb6a218c34f33R7-R8) in #54)
This PR includes some failed attempts to fix that.
Next steps: probably switch to [lalrpop](https://github.com/lalrpop/lalrpop) or [pom](https://github.com/J-F-Liu/pom) 👀
=> Attempt to fix slow pest parser 😞 

.gitattributes, crates/ditto-checker/src/result/mod.rs, crates/ditto-codegen-js/src/lib.rs, crates/ditto-codegen-js/src/render.rs, crates/ditto-config/src/tests.rs, crates/ditto-cst/src/parser/tests/mod.rs, crates/ditto-fmt/src/config.rs, crates/ditto-fmt/src/lib.rs, crates/ditto-make/src/build_ninja.rs, crates/snapshot-test/README.md, crates/snapshot-test/src/lib.rs
I'll defer to [Prettier](https://prettier.io/docs/en/options.html#end-of-line) for the reasoning 💅  But if nothing else it makes running the ditto tests across all the operating systems much easier/simpler.
=> Stop messing around with line endings, just use LF 👨‍⚖️

crates/ditto-ast/src/expression.rs, crates/ditto-checker/src/typechecker/mod.rs, crates/ditto-checker/src/typechecker/substitution.rs
This is in anticipation of type aliases (#62).
The motivating example is:
```ditto
type alias WholeNumber = Int;
five : WholeNumber = 5;
```
Currently we would drop the alias type annotation as part of type checking, but we want to keep it around for more helpful type errors.
=> Store literal expression type in the AST

crates/ditto-ast/src/expression.rs, crates/ditto-checker/src/module/value_declarations/mod.rs, crates/ditto-checker/src/typechecker/mod.rs, crates/ditto-checker/src/typechecker/pre_ast.rs, crates/ditto-checker/src/typechecker/substitution.rs, crates/ditto-checker/src/typechecker/tests/effect.rs, crates/ditto-codegen-js/golden-tests/javascript/effect_expressions.ditto, crates/ditto-codegen-js/golden-tests/javascript/effect_expressions.js, crates/ditto-codegen-js/golden-tests/javascript/irrefutable_argument_patterns.js, crates/ditto-codegen-js/src/convert.rs, crates/ditto-codegen-js/src/optimize/mod.rs, crates/ditto-cst/src/ditto.lalrpop, crates/ditto-cst/src/expression.rs, crates/ditto-cst/src/parser/tests/expression.rs, crates/ditto-fmt/golden-tests/effect_expressions.ditto, crates/ditto-fmt/src/expression.rs, crates/ditto-fmt/src/has_comments.rs, crates/ditto-fmt/src/token.rs
This allows pure variable binding in `Effect` blocks. For example:
```ditto
main = do {
let five: Int = 5;
return five
};
```
Of course the above is a bit redundant (and should probably be rewritten as part of the JS codegen 👀 ) but this is useful in less trivial cases.
It's particularly useful as [we don't currently support patterns on the left-hand side of effect binds](https://github.com/ditto-lang/ditto/issues/59#issuecomment-1298362282) (`<-`, due to parsing restrictions).
So eventually this will be nice for code like:
```ditto
main = do {
env <- get_env();
let { foo } = env;
return foo
};
```
Also note that as part of this I had to add a fresh variable `supply` to the JavaSCript code generator, so that we can use generated variables without risking bad `const` assignments (i.e. …
=> Support `let` bindings in `Effect` blocks

crates/ditto-ast/src/expression.rs, crates/ditto-checker/src/module/value_declarations/mod.rs, crates/ditto-checker/src/typechecker/mod.rs, crates/ditto-checker/src/typechecker/pre_ast.rs, crates/ditto-checker/src/typechecker/substitution.rs, crates/ditto-checker/src/typechecker/tests/records.rs, crates/ditto-codegen-js/src/ast.rs, crates/ditto-codegen-js/src/convert.rs, crates/ditto-codegen-js/src/optimize/mod.rs, crates/ditto-codegen-js/src/render.rs, crates/ditto-codegen-js/tests/golden/objects.ditto, crates/ditto-codegen-js/tests/golden/objects.js, crates/ditto-cst/src/ditto.lalrpop, crates/ditto-cst/src/expression.rs, crates/ditto-cst/src/get_span.rs, crates/ditto-cst/src/parser/tests/expression.rs, crates/ditto-fmt/src/expression.rs, crates/ditto-fmt/src/has_comments.rs, crates/ditto-fmt/src/syntax.rs, crates/ditto-fmt/tests/golden/value_declarations.ditto
The language now supports: 
```ditto
{ some_record | foo = 2, bar = false }
```
Where `some_record` can be `Expression1` or `Expression0`.
https://github.com/ditto-lang/ditto/blob/b1346ff51de876ae9eab3fdd4d3df96df3e92915/crates/ditto-cst/src/ditto.lalrpop#L138-L164
**Note** that record updates a) do not support adding new fields to a record and b) do not support changing the type of an existing record field. These choices are stolen from [Erlang](https://www.erlang.org/doc/efficiency_guide/maps.html#using-maps-as-an-alternative-to-records) and [Elm](https://github.com/elm/compiler/blob/047d5026fe6547c842db65f7196fed3f0b4743ee/docs/upgrade-instructions/0.19.0.md#stricter-record-update-syntax).
=> Record updates 👌

crates/ditto-codegen-js/src/render.rs, crates/ditto-codegen-js/tests/golden/basic_expressions.ditto, crates/ditto-codegen-js/tests/golden/basic_expressions.js, crates/ditto-codegen-js/tests/golden/objects.js
Under some circumstances TypeScript will infer `[]` as type `never[]`, which was causing problems for me trying to type-check some generated (package) code.
Generating code that is "correct" as far as `tsc` is concerned is important to me, so I think this change is reasonable. 
Note that the empty array _needs_ to be in parentheses for the `@type` comment to apply. Which means `prettier` can break this 😬 
[See this Stack Overflow answer](https://stackoverflow.com/a/70101585)
=> Type annotate empty arrays (with JSDoc)

Cargo.lock, crates/ditto-cli/Cargo.toml, crates/ditto-cli/src/pkg.rs, crates/ditto-config/src/package_set.rs, crates/ditto-config/src/tests.rs
Extends the `PackageSpec` type to support GitHub repositories and updates the install logic.
A GitHub package dependency is specified like:
```toml
[package-set.packages.js-ref]
github = { owner = "ditto-lang", repo = "js-ref" }     # inspired by Nix's fetchFromGitHub
revision = "fb8a458da5a9394afc199974ed880bf9e99c7571"
sha256 = "a25b7f0f65ce48157ca6ff536b675c7fdd1383c6b901991257328bbd6189cf3d"
```
The install logic is then:
1. `GET https://github.com/{github.owner}/{github.repo}/archive/{revision}.zip`
2. Check that the sha256 matches
3. Store the downloaded zip archive in the cache, using the sha256 as the key (much like [Nix](https://nixos.org/))
4. Unpack contents of the archive into the current project's package directory
And if the entry already exists in the cache, we skip …
=> Add support for github packages :octocat: 

crates/ditto-codegen-js/src/convert.rs, crates/ditto-codegen-js/src/optimize/mod.rs, crates/ditto-codegen-js/tests/golden/basic_expressions.js, crates/ditto-codegen-js/tests/golden/effect_expressions.js, crates/ditto-codegen-js/tests/golden/unused_patterns.ditto, crates/ditto-codegen-js/tests/golden/unused_patterns.js
The following is legal ditto code:
```ditto
ignore_both_args = fn (_, _) -> 5;
```
But currently that will generate the following JavaScript:
```js
function ignore_both_args(_, _) {
return 5;
}
```
Which will raise an error to the effect of: `SyntaxError: Duplicate parameter name not allowed in this context`.
Hence, we need to ensure that unused identifiers are unique.
=> Fix unused JavaScript identifiers :wrench: 

crates/ditto-ast/src/lib.rs, crates/ditto-ast/src/type.rs, crates/ditto-checker/src/typechecker/mod.rs, crates/ditto-checker/tests/cmd/function_type_alias/test.stdin, crates/ditto-checker/tests/cmd/function_type_alias/test.stdout, crates/ditto-checker/tests/cmd/function_type_alias/test.toml, crates/ditto-checker/tests/trycmd_tests.rs
The issue boils down to:
```ditto
module Test exports (five);
type alias Identity(a) = (a) -> a;
five = identity_impl(5);
foreign identity_impl: Identity(a);
```
Because we check as part of `Call` expressions whether the thing being called is/looks callable. But that wasn't taking into account type aliases.
Also note that this issue only surfaces when using foreign imports. The following will not complain:
```ditto
identity : Identity(a) = fn (a) -> a;
```
Because we're not hanging on to that type annotation anywhere :grimacing: I'm gonna fix that...
=> Fix aliased function type checking

crates/ditto-ast/src/expression.rs, crates/ditto-checker/src/typechecker/mod.rs, crates/ditto-checker/src/typechecker/substitution.rs, crates/ditto-checker/src/typechecker/tests/records.rs, crates/ditto-checker/tests/cmd/always_partial_application/test.stdout, crates/ditto-checker/tests/cmd/closed_record_alias/test.stdout, crates/ditto-checker/tests/cmd/duplicate_type_import/test.out/Maybe.ast, crates/ditto-checker/tests/cmd/duplicate_type_import_with_different_visibility/test.out/Maybe.ast, crates/ditto-checker/tests/cmd/duplicate_value_import/test.out/Foo.ast, crates/ditto-checker/tests/cmd/export_docs/test.stdout, crates/ditto-checker/tests/cmd/float_alias/test.stdout, crates/ditto-checker/tests/cmd/foreign_value_impl/test.stdout, crates/ditto-checker/tests/cmd/homogeneous_type_alias_array/test.stdout, crates/ditto-checker/tests/cmd/imported_constructor_matching/test.out/Dep.ast, crates/ditto-checker/tests/cmd/imported_constructor_matching/test.stdout, crates/ditto-checker/tests/cmd/maybe_int_alias/test.stdout, crates/ditto-checker/tests/cmd/mini_vdom/test.stdout, crates/ditto-checker/tests/cmd/never/test.stdout, crates/ditto-checker/tests/cmd/open_record_alias/test.stdout, crates/ditto-checker/tests/cmd/open_record_alias_chain/test.stdout, crates/ditto-checker/tests/cmd/option_alias/test.stdout, crates/ditto-checker/tests/cmd/record_extension_newtype/test.stdout, crates/ditto-checker/tests/cmd/result_alias_effect_matching/test.stdout, crates/ditto-checker/tests/cmd/result_alias_matching/test.stdout, crates/ditto-checker/tests/cmd/simple_type_imports/test.out/Maybe.ast, crates/ditto-checker/tests/cmd/simple_value_imports/test.out/Foo.ast, crates/ditto-checker/tests/cmd/unused_value_declaration/test.stdout, crates/ditto-checker/tests/cmd/variable_alias/test.stdin, crates/ditto-checker/tests/cmd/variable_alias/test.stdout, crates/ditto-checker/tests/trycmd_tests.rs
[As promised](https://github.com/ditto-lang/ditto/pull/111#issue-1511819930)...
> Because we're not hanging on to that type annotation anywhere grimacing I'm gonna fix that...
We now properly store type annotations. Which is important since type aliases were introduced in #62.
=> Store any type annotations in the AST

crates/ditto-codegen-js/src/convert.rs, crates/ditto-codegen-js/src/optimize/mod.rs, crates/ditto-codegen-js/tests/golden/match_expressions.ditto, crates/ditto-codegen-js/tests/golden/match_expressions.js
Updates the JavaScript code generator to assign expressions being matched against. This avoids potentially expensive re-evaluations.
Given the following module:
```ditto
module Example exports (..);
some = fn (a) -> a;
long = fn (a) -> a;
convoluted = fn (a) -> a;
function = fn (a) -> a;
type ABC =
| A(Int)
| B(Int)
| C(Int);
example = fn (abc) ->
match abc
|> some
|> long
|> convoluted
|> function with
| A(i) -> i
| B(i) -> i
| C(i) -> i
end;
```
Before this PR would generate:
```js
function example(abc) {
if ($function(convoluted(long(some(abc))))[0] === "A") {
const i = $function(convoluted(long(some(abc))))[1];
return i;
}
if ($function(convoluted(long(some(abc))))[0] === "B") {
const i = $function(convoluted(long(some(abc))))[1];
return i;
}
if …
```
=> Assign matched expressions to variables in generated JavaScript ⚡

crates/ditto-checker/src/bin/ditto-checker-testbin-check-module.rs, crates/ditto-checker/src/kindchecker/mod.rs, crates/ditto-checker/src/typechecker/common.rs, crates/ditto-checker/src/typechecker/env.rs, crates/ditto-checker/src/typechecker/mod.rs, crates/ditto-checker/src/typechecker/scheme.rs, crates/ditto-checker/src/typechecker/substitution.rs, crates/ditto-checker/tests/cmd/basic_task_module/test.stdin, crates/ditto-checker/tests/cmd/basic_task_module/test.stdout, crates/ditto-checker/tests/cmd/basic_task_module/test.toml, crates/ditto-checker/tests/cmd/function_type_alias/test.stdout, crates/ditto-checker/tests/cmd/variable_alias/test.stdout
This (I think) is the correct fix for the bug described in #115. 
Note that I'm still swapping out `HashSet` for `IndexSet` because we need the determinism for tests.
=> Fix type alias substitution

crates/ditto-make/src/build_ninja.rs, crates/ditto-make/tests/cmd/unsupported-ditto-version/test.stderr
I tried adding a required ditto version to https://github.com/ditto-lang/std
```diff
diff --git a/ditto.toml b/ditto.toml
index 835b5b2..691be46 100644
--- a/ditto.toml
+++ b/ditto.toml
@@ -1,5 +1,6 @@
name = "std"
targets = ["web", "nodejs"]
+ditto-version = ">=0.0.2"
```
But that complained with:
```
× error generating build.ninja
╰─▶ ditto version requirement not met for current_package: current version = 0.0.2-1-g2ea38ab, wanted = >=0.0.2
```
Maybe there's a way to specify in the requirement that `pre` should be ignored, but I also think `ditto-version = ">=0.0.2"` should just work. This PR makes it so.
_(I also took the underscore out of `current_package` while I was there)_
=> Fix required ditto version checking

crates/ditto-codegen-js/src/render.rs, crates/ditto-codegen-js/tests/golden/strings.ditto, crates/ditto-codegen-js/tests/golden/strings.js, crates/ditto-cst/src/lexer.rs
Check that some fancier features of string literals work as expected.
This is in anticipation of #65 :eyes:
=> Ensure that multiline strings and escapes work as expected

Cargo.lock, crates/ditto-cli/Cargo.toml, crates/ditto-cli/src/common.rs, crates/ditto-cli/src/main.rs, crates/ditto-cli/src/make.rs, crates/ditto-cli/src/ninja.rs, crates/ditto-cli/src/pkg.rs, crates/ditto-lsp/Cargo.toml, crates/ditto-lsp/src/lib.rs, crates/ditto-make/Cargo.toml, crates/ditto-make/src/build_ninja.rs, crates/ditto-make/src/common.rs, crates/ditto-make/src/compile.rs, shell.nix
I was using [`log`](https://crates.io/crates/log) but the cool kids seem to be using [`tracing`](https://crates.io/crates/tracing) 😎 
The big selling point for me is [`tracing-flame`](https://crates.io/crates/tracing-flame) which means I can generate flamegraphs and start identifying bottlenecks 🧐 
```console
$ rm -rf .ditto   # with a clean build
$ DITTO_TRACE_DIR=.ditto/traces ditto make
$ cat .ditto/traces/* | inferno-flamegraph --flamechart > flamegraph.svg
PROFIT
```
=> Switch to `tracing` + flamegraphs 🔥

crates/ditto-make/src/compile.rs
The [flamegraphs](https://github.com/ditto-lang/ditto/pull/183#issuecomment-1423825670) from #183 showed that `ditto make` was spending a _significant_ amount of time serializing and deserializing. 
Making this change gives a **big** speedup, so I'm pretty sure that was the problem. Although switching to something like [`bincode`](https://docs.rs/bincode/latest/bincode/) could also be worthwhile? #184
Typechecking modules is now the bottleneck, which is what I'd expect.
=> Use `BufReader` and `BufWriter` more 🤦

crates/ditto-fmt/src/expression.rs, crates/ditto-fmt/src/syntax.rs, crates/ditto-fmt/src/type.rs, crates/ditto-fmt/tests/golden/records.ditto
Under some circumstances record formatting was misbehaving.
A good example is some code from the (upcoming 👀) playground (diff is before and after this change):
```diff
diff --git a/ditto-src/Main.ditto b/ditto-src/Main.ditto
index 25a7bc4..90c02f8 100644
--- a/ditto-src/Main.ditto
+++ b/ditto-src/Main.ditto
@@ -242,8 +242,7 @@ update = fn (state: State, event: Event): Next ->
task = Just(Task.succeed(CompileClicked)),
}
| EditorInitError(error) -> {
-        state = {
-            state |editor = EditorInitFailed(error)},
+        state = { state | editor = EditorInitFailed(error) },
task = Nothing,
}
| EditorUnmounted -> {
@@ -285,8 +284,7 @@ update = fn (state: State, event: Event): Next ->
task = Nothing,
}
| CompilerInitError(error) -> {
-        state = {
-            state …
```
=> Fix record formatting bug 🐛 

crates/ditto-codegen-js/src/convert.rs, crates/ditto-codegen-js/tests/golden/match_expressions.ditto, crates/ditto-codegen-js/tests/golden/match_expressions.js
The order of conditions generated by a `match` expression is significant (we depend on the short-circuiting of `&&`) and the generated order was wrong. This PR fixes it.
=> Fix bug in generated JS condition order 🐞 

Cargo.lock, crates/ditto-cli/Cargo.toml, crates/ditto-cli/src/main.rs, crates/ditto-cli/src/make.rs, crates/ditto-make/src/build_ninja.rs, crates/ditto-make/src/common.rs, crates/ditto-make/src/compile.rs
`DITTO_LOG_DIR` is no more, now all logs are written to a single file: `DITTO_LOG_FILE` 🙌 .
Those logs are also now structured (JSON) and include span timings, which will be useful for performance analysis. 
It _might_ make sense to support opt-in human-readable logs, but I'll add that as/when necessary.
=> Logging improvements 📡 

scripts/log-analysis/.gitignore, scripts/log-analysis/main.R, scripts/log-analysis/shell.nix
Following #211 this is a little script to help with identifying performance bottlenecks.
For example, I generated build logs for https://github.com/ditto-lang/playground/tree/cd5185b2ccc2fdc1c0b454dbed05dfcb61157a0f using:
```console
$ ditto make
$ rm -rf .ditto/build
$ DITTO_LOG_FILE=logs.ndjson ditto make
```
Then ran this script with:
```console
$ nix-shell --command 'R -s -f main.R'
```
Which gave me: 
Which is quite interesting 🤔
=> Add R script for analysing log span timings
